//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::notes::Entity as Notes;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
